# Use project-root discovery-service folder as build context
FROM maven:3.9.5-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY ../discovery-service /workspace
RUN mvn -B -f /workspace/pom.xml -DskipTests package

FROM eclipse-temurin:21-jre-jammy
COPY --from=build /workspace/target/*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","/app.jar"]
