FROM maven:3.9.5-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY ../listing-service /workspace
RUN mvn -B -f /workspace/pom.xml -DskipTests package

FROM eclipse-temurin:21-jre-jammy
RUN groupadd --system appgroup && useradd --system --gid appgroup appuser
WORKDIR /app
COPY --from=build /workspace/target/*.jar app.jar
RUN chown appuser:appgroup app.jar
USER appuser
EXPOSE 9090
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
